version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.16

## Customize the test machine
machine:

  timezone:
    America/Los_Angeles # Set the timezone

version: 2.1
## Customize dependencies
dependencies:
  override:
    - npm install
    # - npm install -g hexo
    - npm install -g hexo-cli

## Customize test commands
test:
 override:
   - echo "testing"

## Customize deployment commands
deployment:
  prod:
    branch: master
    commands:
      - hexo clean
      - hexo generate
      - aws s3 sync public/ <s3://your-s3-bucket.com/>